/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-bright": "#f9f9f9",
        "on-secondary-fixed": "#002106",
        "deep-charcoal": "#1C1C1C",
        "on-tertiary": "#ffffff",
        "ai-tint": "rgba(226, 55, 68, 0.05)",
        "background": "#f9f9f9",
        "on-surface": "#1a1c1c",
        "surface-container-lowest": "#ffffff",
        "error": "#ba1a1a",
        "primary-fixed-dim": "#ffb3b1",
        "primary-container": "#db313f",
        "surface-white": "#FFFFFF",
        "inverse-surface": "#2f3131",
        "tertiary-fixed-dim": "#ffba43",
        "surface-container-high": "#e8e8e8",
        "surface": "#f9f9f9",
        "on-secondary-fixed-variant": "#00531b",
        "secondary-fixed-dim": "#71dd7c",
        "tertiary": "#7c5400",
        "outline": "#8f6f6e",
        "surface-container-highest": "#e2e2e2",
        "on-primary": "#ffffff",
        "on-secondary-container": "#007328",
        "on-tertiary-fixed-variant": "#614000",
        "error-container": "#ffdad6",
        "cool-gray": "#696969",
        "surface-container": "#eeeeee",
        "border-light": "#E8E8E8",
        "on-secondary": "#ffffff",
        "surface-dim": "#dadada",
        "outline-variant": "#e4bebc",
        "tertiary-container": "#9d6b00",
        "on-surface-variant": "#5b403f",
        "inverse-on-surface": "#f0f1f1",
        "on-primary-container": "#fffbff",
        "on-tertiary-container": "#fffbff",
        "primary-fixed": "#ffdad8",
        "secondary-fixed": "#8dfa96",
        "tertiary-fixed": "#ffddaf",
        "surface-variant": "#e2e2e2",
        "primary": "#b7122a",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#410007",
        "on-primary-fixed-variant": "#92001c",
        "on-background": "#1a1c1c",
        "surface-tint": "#bb162c",
        "inverse-primary": "#ffb3b1",
        "on-error": "#ffffff",
        "secondary-container": "#8af793",
        "on-tertiary-fixed": "#281800",
        "secondary": "#006e26",
        "surface-container-low": "#f3f3f3"
      },
      "borderRadius": {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      "spacing": {
        "stack-gap": "1rem",
        "gutter": "1.5rem",
        "touch-target": "3rem",
        "section-gap": "2.5rem",
        "container-max": "768px"
      },
      "fontFamily": {
        "label-caps": ["Plus Jakarta Sans"],
        "ai-verdict": ["Plus Jakarta Sans"],
        "body-lg": ["Plus Jakarta Sans"],
        "headline-md": ["Plus Jakarta Sans"],
        "headline-lg": ["Plus Jakarta Sans"],
        "headline-lg-mobile": ["Plus Jakarta Sans"],
        "body-sm": ["Plus Jakarta Sans"]
      },
      "fontSize": {
        "label-caps": ["12px", {"lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "600"}],
        "ai-verdict": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}],
        "body-lg": ["16px", {"lineHeight": "1.6", "fontWeight": "400"}],
        "headline-md": ["20px", {"lineHeight": "1.4", "fontWeight": "700"}],
        "headline-lg": ["32px", {"lineHeight": "1.2", "letterSpacing": "-0.04em", "fontWeight": "800"}],
        "headline-lg-mobile": ["24px", {"lineHeight": "1.2", "letterSpacing": "-0.02em", "fontWeight": "800"}],
        "body-sm": ["14px", {"lineHeight": "1.5", "fontWeight": "400"}]
      }
    },
  },
  plugins: [],
}
